package co.smartreceipts.android.imports

object RequestCodes {

    const val NEW_RECEIPT_CAMERA_IMAGE = 3
    const val ATTACH_CAMERA_IMAGE = 4
    const val NEW_RECEIPT_IMPORT_IMAGE = 5
    const val NEW_RECEIPT_IMPORT_PDF = 6
    const val RETAKE_CAMERA_IMAGE = 8
    const val ATTACH_GALLERY_IMAGE = 9
    const val ATTACH_GALLERY_PDF = 10

    const val NEW_RECEIPT_CAMERA_IMAGE_CROP = 11
    const val NEW_RECEIPT_IMPORT_IMAGE_CROP = 12
    const val EDIT_IMAGE_CROP = 13
    const val ATTACH_GALLERY_IMAGE_CROP = 14
    const val ATTACH_CAMERA_IMAGE_CROP = 15


    @JvmField
    val PHOTO_REQUESTS = listOf(
        NEW_RECEIPT_CAMERA_IMAGE,
        ATTACH_CAMERA_IMAGE,
        NEW_RECEIPT_IMPORT_IMAGE,
        RETAKE_CAMERA_IMAGE,
        ATTACH_GALLERY_IMAGE
    )

    @JvmField
    val PDF_REQUESTS = listOf(NEW_RECEIPT_IMPORT_PDF, ATTACH_GALLERY_PDF)

    @JvmField
    val CROP_REQUESTS = listOf(NEW_RECEIPT_CAMERA_IMAGE_CROP, NEW_RECEIPT_IMPORT_IMAGE_CROP,
        EDIT_IMAGE_CROP, ATTACH_GALLERY_IMAGE_CROP, ATTACH_CAMERA_IMAGE_CROP)

}
