name: Android CI - Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  Publish:
    strategy:
      matrix:
        build: [ publishFreeReleaseBundle, publishPlusFlavorBundle]

    needs: Unit-Tests    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_KEY }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Bump Version
      run: |
        export SR_BUILD_NUMBER=${{ github.run_number }}
        cd scripts
        ./version-bumper.sh
    - name: Decrypt secrets
      run: |
        gpg --decrypt secrets.tar.gpg > secrets.tar
        tar -vxf secrets.tar
        rm secrets.tar
    - name: Publish Free Beta Version To Play Store
      run: |
          rm -fr ~/.gradle/daemon/
          ./gradlew ${{ matrix.build }}
      env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

  Unit-Tests:
    uses: ./.github/workflows/unit_tests.yml
  UI-Tests:
    uses: ./.github/workflows/ui_tests.yml
    secrets: inherit

    